name: smart_trip_ai
description: "Smart Trip AI is an AI based travel itinerary planning application which solves the complexity of decision-making in modern travelling while being conscious about user budget. Most travelers rely on multiple platforms just to complete a single destination, accommodation and plan the activities for the whole Trip. The use of multiple platforms results in ineffective decision making and poor travel itineraries ruining the trip journey. Students, first-time tourists, and budget-travelers mostly face these challenges. The aim of Smart Trip AI is to provide a single platform to generate a personalized travel itinerary while being aware of user preferences and budget. Smart Trip AI used AI-based recommendation techniques to analyze travel budgets, travel interest, destination types, duration, and activities. Based on these inputs, Smart Trip AI generates an itinerary for the whole duration of trip including the accommodation, planning the activities and must visit nearby places while being aware of user’s budget. By integrating multiple components relating to travelling, this application reduces manual effort and time and enhances the overall experience of trip. The expected result of this application is to enhance the travel planning and experience by generating editable travel itinerary within user’s budget option. Smart Trip AI reduces the burden of travel plans by recommending the best option that is suitable for the user. Overall, the system shows that the use of Artificial Intelligence in travel planning can help to improve the best experience and options on a trip for budget travelers."

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.8
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
